### Root Endpoint
GET http://localhost:3000

### Add a New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "party",
  "content": "welcome to party",
  "owner": "chen"
}

### Get All Posts
GET http://localhost:3000/posts

### Get Post by ID
GET http://localhost:3000/posts/6748c54e0ce42e38e013d03c

### Get Post by Owner
GET http://localhost:3000/posts?owner=avital

### Update a Post
PUT http://localhost:3000/posts/67499a3d9581b8edfee52724
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "This is the updated content of the post"
}

### Add a New Comment on a Post
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "6749c8f98eca9d034f059826",
  "content": "im coming!!!!!",
  "author": "avital"
}

### Get All Comments
GET http://localhost:3000/comments

### Get All Comments by Post ID
GET http://localhost:3000/comments?postId=6749c45b905aafe29e171b8f

### Update a Comment
PUT http://localhost:3000/comments/6749c90d8eca9d034f059828
Content-Type: application/json

{
  "content": "not coming!!!"
}

### Delete a Comment
DELETE http://localhost:3000/comments/6749c90d8eca9d034f059828
