###
GET http://localhost:3000

### get all posts
GET http://localhost:3000/posts

### get post by id
GET http://localhost:3000/posts/6748c54e0ce42e38e013d03c

### get post by owner
GET http://localhost:3000/posts?owner=avital

### create a post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "party",
  "content": "welcome to party",
  "owner": "chen"
}

### update a post
PUT http://localhost:3000/posts/67499a3d9581b8edfee52724
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "This is the updated content of the post"
}

### create a new comment on a post
POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "6749c8f98eca9d034f059826",
    "content": "im coming!!!!!",
    "author": "avital"
}

### create a new comment
GET http://localhost:3000/comments

### get all comments by a post id
GET http://localhost:3000/comments?postId=6749c45b905aafe29e171b8f

### update a comment
PUT http://localhost:3000/comments/6749c90d8eca9d034f059828
Content-Type: application/json

{
  "content": "not coming!!!"
}
