###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My sec post",
    "content": "This is my sec post"
}

###
GET http://localhost:3000/posts/67499a3d9581b8edfee52724

###
PUT http://localhost:3000/posts/67499a3d9581b8edfee52724
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "This is the updated content of the post"
}
