### Root Endpoint
GET http://localhost:3000

### Add a New Post
POST http://localhost:3000/posts/Avital
Content-Type: application/json

{
  "title": "party",
  "content": "whats up"
}

### Get All Posts
GET http://localhost:3000/posts

### Get Post by ID
GET http://localhost:3000/posts/677d389414a656309ed97965

### Get Post by Owner
GET http://localhost:3000/posts?owner=Chen

### Update a Post
PUT http://localhost:3000/posts/677d389414a656309ed97965
Content-Type: application/json

{
  "title": "party cancalled",
  "content": "we are sorry to inform you that the party is cancalled"
}

### Add a New Comment on a Post
POST http://localhost:3000/comments
Content-Type: application/json

{
  "comment": "hello",
  "postId": "6749d9b4c81ceefb853d0596",
  "owner": "Chen"
}

### Get All Comments
GET http://localhost:3000/comments

### Get All Comments by Post ID
GET http://localhost:3000/comments?677d3fa9323fc02fc6d3e347

### Update a Comment
PUT http://localhost:3000/comments/677d3fa9323fc02fc6d3e347
Content-Type: application/json

{
  "content": "bye!"
}

### Delete a Comment
DELETE http://localhost:3000/comments/677d3fa9323fc02fc6d3e347
